### ISSUE TITLE
Multi-Word CLI Arugments Not Respected

### ISSUE THREAD

**Issue by bryanculver** [rtfpessoa/dependency_spy#15]
**Describe the bug**
When passing in a CLI argument that is handled by Thor's `method_option`, multi-word arguments are [accessed by a symbol](https://github.com/rtfpessoa/dependency_spy/blob/master/lib/dependency_spy.rb#L36) instead of the string it's keyed on. This works for single word arguments as the symbolization is seamless.

The only option I can see that is affected by this is currently `database-path`

**To Reproduce**
1. Clone repo
2. Execute `bundle exec bin/depspy check --database-path="/an/invalid/path"`
3. See list of vulns, as it's defaulting to `YAVDB::Constants::DEFAULT_YAVDB_DATABASE_PATH`

**Expected behavior**
1. Execute `bundle exec bin/depspy check --database-path="/an/invalid/path"`
2. See no vulns as database is empty/invalid

**Screenshots**
Modified `dependency_spy.rb` to show options handling output:
```ruby
module DependencySpy
  class API

    def self.check(options)

      puts "=== Options Input:"
      puts options
      puts "=== Single Word Key"
      puts options["files"]
      puts options[:files]
      puts "=== Multi-Word Key"
      puts options["database-path"]
      puts options[:database_path]

      # ...
      # Original Options Handling
      # ...

      puts "=== Post Options Handling"
      puts files
      puts database_path
#...
```

Output of logging:
```
bundle exec bin/depspy check --files=Gemfile,Gemfile.lock --database-path="/an/invalid/path"
=== Options Input:
{"verbose"=>false, "path"=>"/Users/bryanculver/Workspace/Repos/OpenSource/dependency_spy", "formatter"=>"text", "database-path"=>"/an/invalid/path", "offline"=>false, "severity-threshold"=>"low", "with-color"=>true, "ignore"=>[], "files"=>"Gemfile,Gemfile.lock"}
=== Single Word Key
Gemfile,Gemfile.lock
Gemfile,Gemfile.lock
=== Multi-Word Key
/an/invalid/path

=== Post Options Handling
Gemfile,Gemfile.lock
/Users/bryanculver/.yavdb/yavdb/database
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Ruby Version 2.5.5
 - Bundler Version: 1.17.3
 - Version `@master`/`v0.5.0`

**Additional context**
Discovered this while looking to implement #5.

**Comment by rtfpessoa** [comment]
@bryanculver thanks for catching this bug. I will take a look at the PR.
