### ISSUE TITLE
Support configuration file

### ISSUE THREAD

**Issue by rtfpessoa** [rtfpessoa/dependency_spy#5]
Add support for a configuration file where the user can specify:
* Files/Globs to check
* Files/Globs to ignore
* Package managers to check
* Vulnerabilities to ignore

e.g.: `.depspy.yaml`, `.depspy.yml`, `.depspy.json`.

**Comment by bryanculver** [comment]
@rtfpessoa I am thinking the order of precedence for the configuration would be:

- Command Line Args
- Config File
- Default Values

**Comment by rtfpessoa** [comment]
@bryanculver :+1:
